export const ESTADISTICA_RESUMEN_REQUEST = "ESTADISTICA_RESUMEN_REQUEST";
export const ESTADISTICA_RESUMEN_SUCCESS = "ESTADISTICA_RESUMEN_SUCCESS";
export const ESTADISTICA_RESUMEN_FAIL = "ESTADISTICA_RESUMEN_FAIL";

export const ESTADISTICA_INGRESOS_REQUEST = "ESTADISTICA_INGRESOS_REQUEST";
export const ESTADISTICA_INGRESOS_SUCCESS = "ESTADISTICA_INGRESOS_SUCCESS";
export const ESTADISTICA_INGRESOS_FAIL = "ESTADISTICA_INGRESOS_FAIL";

export const ESTADISTICA_METODOS_REQUEST = "ESTADISTICA_METODOS_REQUEST";
export const ESTADISTICA_METODOS_SUCCESS = "ESTADISTICA_METODOS_SUCCESS";
export const ESTADISTICA_METODOS_FAIL = "ESTADISTICA_METODOS_FAIL";

export const ESTADISTICA_GASTOS_REQUEST = "ESTADISTICA_GASTOS_REQUEST";
export const ESTADISTICA_GASTOS_SUCCESS = "ESTADISTICA_GASTOS_SUCCESS";
export const ESTADISTICA_GASTOS_FAIL = "ESTADISTICA_GASTOS_FAIL";