export const FACTURA_LIST_REQUEST = "FACTURA_LIST_REQUEST";
export const FACTURA_LIST_SUCCESS = "FACTURA_LIST_SUCCESS";
export const FACTURA_LIST_FAIL = "FACTURA_LIST_FAIL";

export const FACTURA_CREATE_REQUEST = "FACTURA_CREATE_REQUEST";
export const FACTURA_CREATE_SUCCESS = "FACTURA_CREATE_SUCCESS";
export const FACTURA_CREATE_FAIL = "FACTURA_CREATE_FAIL";

export const FACTURA_DETAIL_REQUEST = "FACTURA_DETAIL_REQUEST";
export const FACTURA_DETAIL_SUCCESS = "FACTURA_DETAIL_SUCCESS";
export const FACTURA_DETAIL_FAIL = "FACTURA_DETAIL_FAIL";
export const FACTURA_CREATE_RESET = "FACTURA_CREATE_RESET";