export const GASTO_LIST_REQUEST = "GASTO_LIST_REQUEST";
export const GASTO_LIST_SUCCESS = "GASTO_LIST_SUCCESS";
export const GASTO_LIST_FAIL = "GASTO_LIST_FAIL";

export const GASTO_CREATE_REQUEST = "GASTO_CREATE_REQUEST";
export const GASTO_CREATE_SUCCESS = "GASTO_CREATE_SUCCESS";
export const GASTO_CREATE_FAIL = "GASTO_CREATE_FAIL";

export const GASTO_UPDATE_REQUEST = "GASTO_UPDATE_REQUEST";
export const GASTO_UPDATE_SUCCESS = "GASTO_UPDATE_SUCCESS";
export const GASTO_UPDATE_FAIL = "GASTO_UPDATE_FAIL";

export const GASTO_DELETE_REQUEST = "GASTO_DELETE_REQUEST";
export const GASTO_DELETE_SUCCESS = "GASTO_DELETE_SUCCESS";
export const GASTO_DELETE_FAIL = "GASTO_DELETE_FAIL";