export const PAGO_LIST_REQUEST = "PAGO_LIST_REQUEST";
export const PAGO_LIST_SUCCESS = "PAGO_LIST_SUCCESS";
export const PAGO_LIST_FAIL = "PAGO_LIST_FAIL";

export const PAGO_CREATE_REQUEST = "PAGO_CREATE_REQUEST";
export const PAGO_CREATE_SUCCESS = "PAGO_CREATE_SUCCESS";
export const PAGO_CREATE_FAIL = "PAGO_CREATE_FAIL";

export const PAGO_ANULAR_REQUEST = "PAGO_ANULAR_REQUEST";
export const PAGO_ANULAR_SUCCESS = "PAGO_ANULAR_SUCCESS";
export const PAGO_ANULAR_FAIL = "PAGO_ANULAR_FAIL";