export const COLA_LIST_REQUEST = "COLA_LIST_REQUEST";
export const COLA_LIST_SUCCESS = "COLA_LIST_SUCCESS";
export const COLA_LIST_FAIL = "COLA_LIST_FAIL";

export const COLA_PENDIENTES_REQUEST = "COLA_PENDIENTES_REQUEST";
export const COLA_PENDIENTES_SUCCESS = "COLA_PENDIENTES_SUCCESS";
export const COLA_PENDIENTES_FAIL = "COLA_PENDIENTES_FAIL";

export const COLA_TERMINADOS_REQUEST = "COLA_TERMINADOS_REQUEST";
export const COLA_TERMINADOS_SUCCESS = "COLA_TERMINADOS_SUCCESS";
export const COLA_TERMINADOS_FAIL = "COLA_TERMINADOS_FAIL";

export const COLA_AGREGAR_REQUEST = "COLA_AGREGAR_REQUEST";
export const COLA_AGREGAR_SUCCESS = "COLA_AGREGAR_SUCCESS";
export const COLA_AGREGAR_FAIL = "COLA_AGREGAR_FAIL";

export const EVENTO_AVANZAR_REQUEST = "EVENTO_AVANZAR_REQUEST";
export const EVENTO_AVANZAR_SUCCESS = "EVENTO_AVANZAR_SUCCESS";
export const EVENTO_AVANZAR_FAIL = "EVENTO_AVANZAR_FAIL";
