export const PRODUCTOS_REQUEST = "PRODUCTOS_REQUEST";
export const PRODUCTOS_SUCCESS = "PRODUCTOS_SUCCESS";
export const PRODUCTOS_FAIL = "PRODUCTOS_FAIL";

export const PEDIDOS_REQUEST = "PEDIDOS_REQUEST";
export const PEDIDOS_SUCCESS = "PEDIDOS_SUCCESS";
export const PEDIDOS_FAIL = "PEDIDOS_FAIL";
